### ISSUE TITLE
White text on sand eye strain

### ISSUE THREAD

**Issue by Dimmerworld** [HearthProject/Website#4]
I think the background or text should be changed to prevent the white on white from forming. To make it easier to see without all the complexities in the background overwhelming it.

**Comment by Rushmead** [comment]
Can you tell me if this looks better?
https://i.pomeroys.site/f0IqHa

**Comment by Dimmerworld** [comment]
Looks like a improvement, I still have a slight urge for the main body of text to have a darker background just to give it the extra readability.

**Comment by Rushmead** [comment]
How about this? http://i.pomeroys.site/Xb9sxV

**Comment by Dimmerworld** [comment]
Yeah that looks fine. Thanks for the change
